"""Applying adapters/postgres/sql/0001_init.sql yields the same catalogue as PostgresStore.migrate()."""
import pathlib
import uuid

import pytest

from harness import pg_dsn

pytestmark = pytest.mark.postgres
MIGRATION = pathlib.Path(__file__).resolve().parents[2] / "packages/wakecore/src/wakecore/adapters/postgres/sql/0001_init.sql"

CATALOGUE = """
SELECT 'col', table_name, column_name || ':' || data_type || ':' || is_nullable
  FROM information_schema.columns WHERE table_schema = %(s)s
UNION ALL
SELECT 'con', rel.relname, con.conname || ':' || pg_get_constraintdef(con.oid)
  FROM pg_constraint con JOIN pg_class rel ON rel.oid = con.conrelid
  JOIN pg_namespace n ON n.oid = rel.relnamespace WHERE n.nspname = %(s)s
UNION ALL
SELECT 'idx', tablename, indexname || ':' || regexp_replace(indexdef, ' ON [^ ]+ ', ' ON ')
  FROM pg_indexes WHERE schemaname = %(s)s
"""


def _catalogue(conn, schema):
    # FK constraint names are generated by PostgreSQL deterministically from the table/columns;
    # definitions may qualify referenced tables with the (random) schema name, so strip it.
    return sorted((k, t, d.replace(f"{schema}.", "")) for k, t, d in conn.execute(CATALOGUE, {"s": schema}))


def test_sql_file_and_runtime_migration_build_identical_schemas():
    import psycopg
    from psycopg.conninfo import make_conninfo

    from wakecore.adapters.postgres.store import PostgresStore

    a, b = ("wk_mig_" + uuid.uuid4().hex[:10] for _ in range(2))
    with psycopg.connect(pg_dsn(), autocommit=True) as c:
        for s in (a, b):
            c.execute(f'CREATE SCHEMA "{s}"')
        try:
            with psycopg.connect(make_conninfo(pg_dsn(), options=f"-c search_path={a}"), autocommit=True) as ca:
                ca.execute(MIGRATION.read_text(encoding="utf-8"))
            store = PostgresStore(make_conninfo(pg_dsn(), options=f"-c search_path={b}"))
            store.migrate()
            store.close()
            got_a, got_b = _catalogue(c, a), _catalogue(c, b)
            assert len(got_a) > 300
            assert got_a == got_b
        finally:
            for s in (a, b):
                c.execute(f'DROP SCHEMA "{s}" CASCADE')
